import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    JWT_SECRET: z.string().min(1),
    SESSION_EXPIRY_DAYS: z.string().default('30'),
    DATABASE_URL: z.string().min(1),
    RESEND_FROM: z.string().optional(),
    RESEND_TOKEN: z.string().optional(),
    BETTERSTACK_API_KEY: z.string().optional(),
    BETTERSTACK_URL: z.string().optional(),
    FLAGS_SECRET: z.string().optional(),
    ARCJET_KEY: z.string().optional(),
    SVIX_TOKEN: z.string().optional(),
    LIVEBLOCKS_SECRET: z.string().optional(),
    BASEHUB_TOKEN: z.string().optional(),
    KNOCK_API_KEY: z.string().optional(),
    KNOCK_FEED_CHANNEL_ID: z.string().optional(),
    KNOCK_SECRET_API_KEY: z.string().optional(),
    VERCEL: z.string().optional(),
    ANALYZE: z.string().optional(),
    API_URL: z.string().default('http://localhost:3000/api/v1/barfer'),
  },
  client: {
    NEXT_PUBLIC_AUTH_SIGN_IN_URL: z.string().default('/sign-in'),
    NEXT_PUBLIC_AUTH_SIGN_UP_URL: z.string().default('/sign-up'),
    NEXT_PUBLIC_AUTH_AFTER_SIGN_IN_URL: z.string().default('/'),
    NEXT_PUBLIC_AUTH_AFTER_SIGN_UP_URL: z.string().default('/'),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
    NEXT_PUBLIC_APP_URL: z.string().default('http://localhost:3000'),
    NEXT_PUBLIC_WEB_URL: z.string().default('http://localhost:3001'),
    NEXT_PUBLIC_WEB_BASE_URL: z.string().default('http://localhost:3007'),
    NEXT_PUBLIC_DOCS_URL: z.string().default('http://localhost:3004'),
    NEXT_PUBLIC_GA_MEASUREMENT_ID: z.string().optional(),
    NEXT_PUBLIC_KNOCK_API_KEY: z.string().optional(),
    NEXT_PUBLIC_KNOCK_FEED_CHANNEL_ID: z.string().optional(),
  },
  runtimeEnv: {
    JWT_SECRET: process.env.JWT_SECRET,
    SESSION_EXPIRY_DAYS: process.env.SESSION_EXPIRY_DAYS,
    DATABASE_URL: process.env.DATABASE_URL,
    RESEND_FROM: process.env.RESEND_FROM,
    RESEND_TOKEN: process.env.RESEND_TOKEN,
    BETTERSTACK_API_KEY: process.env.BETTERSTACK_API_KEY,
    BETTERSTACK_URL: process.env.BETTERSTACK_URL,
    FLAGS_SECRET: process.env.FLAGS_SECRET,
    ARCJET_KEY: process.env.ARCJET_KEY,
    SVIX_TOKEN: process.env.SVIX_TOKEN,
    LIVEBLOCKS_SECRET: process.env.LIVEBLOCKS_SECRET,
    BASEHUB_TOKEN: process.env.BASEHUB_TOKEN,
    KNOCK_API_KEY: process.env.KNOCK_API_KEY,
    KNOCK_FEED_CHANNEL_ID: process.env.KNOCK_FEED_CHANNEL_ID,
    KNOCK_SECRET_API_KEY: process.env.KNOCK_SECRET_API_KEY,
    VERCEL: process.env.VERCEL,
    ANALYZE: process.env.ANALYZE,
    API_URL: process.env.API_URL,
    NEXT_PUBLIC_AUTH_SIGN_IN_URL: process.env.NEXT_PUBLIC_AUTH_SIGN_IN_URL,
    NEXT_PUBLIC_AUTH_SIGN_UP_URL: process.env.NEXT_PUBLIC_AUTH_SIGN_UP_URL,
    NEXT_PUBLIC_AUTH_AFTER_SIGN_IN_URL: process.env.NEXT_PUBLIC_AUTH_AFTER_SIGN_IN_URL,
    NEXT_PUBLIC_AUTH_AFTER_SIGN_UP_URL: process.env.NEXT_PUBLIC_AUTH_AFTER_SIGN_UP_URL,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_WEB_URL: process.env.NEXT_PUBLIC_WEB_URL,
    NEXT_PUBLIC_WEB_BASE_URL: process.env.NEXT_PUBLIC_WEB_BASE_URL,
    NEXT_PUBLIC_DOCS_URL: process.env.NEXT_PUBLIC_DOCS_URL,
    NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    NEXT_PUBLIC_KNOCK_API_KEY: process.env.NEXT_PUBLIC_KNOCK_API_KEY,
    NEXT_PUBLIC_KNOCK_FEED_CHANNEL_ID: process.env.NEXT_PUBLIC_KNOCK_FEED_CHANNEL_ID,
  },
});
